apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smartcontracttest
  annotations:
    github.com/project-slug: alibeknow/smartcontracttest
spec:
  type: other
  lifecycle: unknown
  owner: guests
